### ISSUE TITLE
hassio 0.50 

### ISSUE THREAD

**Issue by encor50** [olivierguerriat/hassio-addons#5]
homebridge is not working with the new version 0.50

**Comment by dobrynski** [comment]
I did not get a chance to get it working previously but now that I've tried with 0.50 I can't add any accessory (iOS on 3 different devices doesn't find homebridge).

Additionally after some time homebridge seems to crash. Here is an example:
```
/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:26
        .setValue(newState.state === 'on', null, 'internal');
                          ^

TypeError: Cannot read property 'state' of null
    at Object.onEvent (/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:26:27)
    at EventSource.HomeAssistantPlatform.es.addEventListener (/usr/lib/node_modules/homebridge-homeassistant/index.js:56:19)
    at emitOne (events.js:96:13)
    at EventSource.emit (events.js:188:7)
    at _emit (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:186:17)
    at parseEventStreamLine (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:201:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:164:11)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
Thanks for your hard work.

Regards,
Michal

P.S. I tried it on an older hassio install (0.49.1) and still could not get iOS to see it.. So there may be another problem at play here.

**Comment by niXta1** [comment]
It stopped working somewhere between .46 and .50.

**Comment by olivierguerriat** [comment]
This add-on is deprecated and doesn't work anymore.

Please uninstall it [and use Franck Nijhof's add-on instead](https://github.com/hassio-addons/repository/tree/master/homebridge). Your configuration should be transferred transparently.
